### PR TITLE
33-b update cice diagnostics for pre-industrial configuration

### PR DESCRIPTION
**Pull request by blimlim**
This pull request completes the portion of https://github.com/ACCESS-NRI/access-esm1.5-configs/issues/33 for the pre-industrial configuration. It:

- Removes diagnostics impacted by the ESM1.5 coupling bug, and adds a comment with brief explanation.

### CODE REVIEW

**Comment by anton-seaice** [comment]
Apologies - i didnt realise this was different to the review on the historical branch .

I checked this out and did payu run (I tried payu-dev and payu-release) and got this error:
```
Traceback (most recent call last):
  File "/g/data/vk83/prerelease/apps/payu/dev/bin/payu", line 8, in <module>
    sys.exit(parse())
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/cli.py", line 41, in parse
    run_cmd(**args)
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/subcommands/sweep_cmd.py", line 16, in runcmd
    expt = Experiment(lab)
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/experiment.py", line 102, in __init__
    self.set_output_paths()
  File "/g/data/vk83/prerelease/apps/payu/dev/lib/python3.10/site-packages/payu/experiment.py", line 362, in set_output_paths
    assert (os.path.isdir(user_restart_dir))
AssertionError
```

I added added "modern" to the restart path, and then I got (on `payu/1.1.3`) :

`FileNotFoundError: Executable for atmosphere model not found on path: /scratch/tm70/as2285/access-esm/bin/um_hg3.exe
`
Switched to payu/dev and it started. Ill update tomorrow. I guess we need to add somewhere (the readme?) it needs payu version >1.1.3. And the input paths need updating before we can make this change.

**Comment by blimlim** [comment]
Ah sorry about this! There's a few changes happening to the configs/filepaths in different places and so this one's not working at the moment. Once the others are merged in I'll bring this one up to date so that it can run, and then will ping you when it's ready!

**Comment by anton-seaice** [comment]
I sanity checked a couple of the output fields (congel, frazil) and they don't exist (as expected)

**Review by anton-seaice — CHANGES_REQUESTED** [review]
Changes are to update the input file paths in a different PR and then update this per comments :)

**Comment by blimlim** [comment]
Closing this PR as selecting CICE diagnostics will be part of setting up the output presets.

**Pull request closed without merging**
